server_name: 'Moonlight Coders'
footer: 'Programmed By dogmoore#3261'
activity: 'Burning the midnight oil again!'
invite_filter: 'please do not send Discord invites'
invite: 'https://discord.gg/kPefMFPQgd'
nickname_length_error: 'This nickname was too long, the limit is 64 characters'
mute_error: 'I can not mute this person'
kick_error: 'I can not kick this user'
ban_error: 'I can not ban this user'
nickname_error: 'I can not nickname this person'